name: unison-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - furo
  - jupyterlab
  - myst-nb
  - pip
  - python=3.10
  - sphinx-autobuild
  - sphinx-copybutton
  - sphinx-inline-tabs
  - rich
  - typer
  - jupyter_client
  - nbformat
  - nbconvert
  - pip:
      - sphinxext-opengraph
      - -e ..
